### ISSUE TITLE
Can't find variable: regeneratorRuntime

### ISSUE THREAD

**Issue by jmutnick** [ljmerza/tracking-number-card#2]
Under HA 0.97.0b3 getting this error:

https://my.ha.site:8123/community_plugin/tracking-number-card/tracking-number-card.js:149:3752 ReferenceError: Can't find variable: regeneratorRuntime

**Comment by ljmerza** [comment]
sorry about that see if 1.2.2 fix es this

**Comment by jmutnick** [comment]
Works now.  Thanks!
