### ISSUE TITLE
HACS Installation Not Working

### ISSUE THREAD

**Issue by carlostico** [ljmerza/tracking-number-card#3]
HACS Installation Not Working, email sensor is showing the emails and count number but the tracking card is not displaying anything

**Comment by ljmerza** [comment]
are any tracking numbers showing up on the email sensor? There's a setting om this card to hide it if no tracking numbers exist

**Comment by awshifts** [comment]
I have a very similar issue, maybe the same.

Here is what it looks like after I configure everything. Thoughts?
![Snag_2c32551d](https://user-images.githubusercontent.com/34609736/68358666-31baea00-00e7-11ea-890d-b9c2642533a2.png)
![Snag_2c32625c](https://user-images.githubusercontent.com/34609736/68358667-31baea00-00e7-11ea-8caf-69175d1d7341.png)

**Comment by ljmerza** [comment]
can you give me the email addresses of the emails that have the tracking numbers?

**Comment by awshifts** [comment]
Dbktracking@gmail.com

**Comment by ljmerza** [comment]
I'm not sure what Dbk tracking is. It's not a supported email

**Comment by awshifts** [comment]
Sorry I gave you the email address the email sensor is supposed to be scanning. When you ask for the email address are you talking about the ups and FedEx email addresses?

**Comment by ljmerza** [comment]
The email sensor works by finding emails that are from certain email
addresses then searching those emails for a tracking number. It doesn't go
through every email and it only searches emails from the supported
providers like ups, USPS, FedEx, etc. If your email isn't coming from one
of the main email addresses that gives tracking numbers I would need to add
it to the list

**Comment by awshifts** [comment]
Makes sense. Email sensor is set to scan my email for UPS and FedEx but nothing shows up on card. A little new to this, but I was pretty sure I have it set up correct

**Comment by ljmerza** [comment]
for ups it only looks for emails ending in 'ups.com' and for fedex ending in 'fedex.com'. if those are different from what you get then id have to add them to the list for each type

**Comment by awshifts** [comment]
I'll try and manually install later tonight -mcinfo@ups.com   is what I have currently in my inbox. I'll let you know, thanks.

**Comment by ljmerza** [comment]
the email might have a different layout from other ups. I'd need a copy of the email to really see whats going on

**Comment by awshifts** [comment]
Was this what you are asking for?

![Snag_340ef480](https://user-images.githubusercontent.com/34609736/68493321-48159280-021a-11ea-82b3-064190f7c580.png)

**Comment by ljmerza** [comment]
I would need the raw email itself. You can forward it to ljmerza@gmail.com

**Comment by awshifts** [comment]
On its way

**Comment by ljmerza** [comment]
so for the UPS parser, it finds the tracking number urls in the email. The first one picks up just fine for me but the other two links point to the same tracking number instead of the tracking you see in the email. Not sure if you noticed this but clicking on any of the three tracking number links all send you to track only the first number. I assume this is a bug on the UPS end

**Comment by awshifts** [comment]
Nothing show up at all for me in the card - I would be happy if it was just one.  I used HACS to set it up, I guess I should try and re-install manually?

**Comment by ljmerza** [comment]
Yeah wouldn't hurt to try installing again. It parses all three links correctly and filters out the duplicates so the first one shows once

**Comment by awshifts** [comment]
I am curious if it is something else.  Manually set it up, but still nothing.  Removing the card from Lovelace shows count 1 but nothing on the card but the header. 

![Snag_42f94bcd](https://user-images.githubusercontent.com/34609736/68592350-dda26380-0460-11ea-92df-7061a3f0205f.png)

**Comment by awshifts** [comment]
So - I have it working now - when I uninstalled I just used HACS above and it would not work.  This third time I downloaded the zip from the Repo, manually copied the files and my Tracking numbers are showing.

**Comment by awshifts** [comment]
I thought maybe it was working but again it is not.   

is there a specific log or item I can look at to see what it is parsing and if its picking up email tracking numbers?  I have checked the parser file itself and the emails I have are coming from FedEx and UPS but it only ever picked up the one and now there are 3 more in the inbox.   If its just my setup that's cool too, i can chalk it up to my environment and move on, either way thanks

**Comment by awshifts** [comment]
Just wanted to leave an update.  All of the UPS ones work but the fedex do not.  Thanks for all you do

**Comment by rpitera** [comment]
I'm not seeing FedEx in my HACS installed version either.  I had a UPS email, it also didn't show but I thought it was something else and I no longer have it to test.  But I have a current one from TrackingUpdates@fedex.com and while the unread count is correct, I'm not seeing the FedEx email in states.  I checked to make sure I have all the dependencies satisfied.  

I'm using my own domain server's email account and I'm not seeing any issues on that end with the connects.  Let me know if I can add any more info.

**Comment by rpitera** [comment]
Just got a UPS tracking email.  Shows in states for the sensor but still nothing in the tracking card.

**Comment by ljmerza** [comment]
I haven't gotten a UPS email in a while but if they've changed the email format or have a different one from the one I used as a template to parse the email, then it would break. This is what this functionality was removed from HA core, it was too fragile. It's hard to see what exactly it is without the email itself.

**Comment by rpitera** [comment]
Would it help if I sent you an email the next time I get one?  What address should I send it to?

I just uninstalled this as this is the second time I've tried working with it.  I got farther this time, actually getting the sensor to work and see emails, but I figured you were busy and gave up.  I'd be glad to try again though.  (BTW, thanks for keeping Our Groceries up to date - love it!)

**Comment by ljmerza** [comment]
you can forward it to ljmerza@gmail.com and I'll take a look

**Comment by rpitera** [comment]
Thanks, I'll do it as soon as a new one comes in.  Might be a bit though.
