### ISSUE TITLE
HACS Download Wrong File

### ISSUE THREAD

**Issue by jdeath** [ljmerza/tracking-number-card#9]
HACS is downloading babel.js instead of tracking-number-card.js . 

Manually downloading the .js file and putting in \config\www\community\tracking-number-card\ works

**Comment by KyleStilkey** [comment]
Same here, adding those 2 files manually to the folder made this start working.

**Comment by frederickjh** [comment]
I am seeing the same here. I have to move the file and delete the babel.js file to get it to work. I allso have to use a manual card entry to use it as it does not show up in the list of available cards.

**Comment by McSwindler** [comment]
The latest release v3.0.2 is missing the `tracking-number-card.js` file as an asset, causing HACS to pull the first available js file in the repo instead.

Reverting to v3.0.1 solves the issue or manually installing the latest version works as well.

**Comment by ljmerza** [comment]
fixed in v3.0.3
